import Head from 'next/head'
import { FC } from 'react'

import { Layout } from '@/components/ui/Layout'

import { Home } from './Home'

export const HomePage: FC = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <Home />
      </Layout>
    </>
  )
}
